// Generated by Xata Codegen 0.30.1.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions
} from "@xata.io/client";

export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Cyrus-s-workspace-pm15qk.ap-southeast-2.xata.sh/db/jsm_doomCast",
    apiKey: process.env.XATA_API_KEY,
    branch: "main"
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
